# Generated by Django 3.1.3 on 2021-02-18 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Householdapp', '0002_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='refrigerator',
            name='unit_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Householdapp.unit'),
            preserve_default=False,
        ),
    ]
