# Generated by Django 3.1.3 on 2021-02-18 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Householdapp', '0003_refrigerator_unit_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refrigerator',
            name='unit_name',
        ),
    ]
