# Generated by Django 3.1.3 on 2021-02-18 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Householdapp', '0004_remove_refrigerator_unit_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
