# Generated by Django 3.1.3 on 2021-02-20 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Householdapp', '0006_auto_20210218_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refrigerator',
            old_name='unit_name',
            new_name='unit',
        ),
    ]
