# Generated by Django 3.1.6 on 2021-02-28 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Householdapp', '0007_auto_20210220_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housekeeping_book',
            name='category',
        ),
        migrations.RemoveField(
            model_name='refrigerator',
            name='grocery',
        ),
        migrations.RemoveField(
            model_name='refrigerator',
            name='unit',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Grocery',
        ),
        migrations.DeleteModel(
            name='Housekeeping_Book',
        ),
        migrations.DeleteModel(
            name='Refrigerator',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
